name: Pull test
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
    Build:
     runs-on: ubuntu-latest
     # container:
        # image: idrigotti/apache
        # credentials:
           # username: ${{ secrets.DOCKERHUB_USERNAME }}
           # password: ${{ secrets.DOCKERHUB_TOKEN }}
     steps: 
       - name: Get Repository
         uses: actions/checkout@v4
       - name: Test
         run: |
           ls -lh
           pwd
       - name: Upload Artifacts
         uses: actions/upload-artifact@v4
         with:
           name: artifacts
           path: |
             /home/runner/work/Actions/Actions/src/piona/HelloWorld.java
             Dockerfile
             index.html
