name: Pull test
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
    Build:
     runs-on: msereno-1S82NM0003BR
     container:
        image: idrigotti/apache
        credentials:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
     steps: 
       - name: Test Pull
         run: java -version