name: Pull test
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
    Build:
     runs-on: copa-runner
     # container:
        # image: idrigotti/apache
        # credentials:
           # username: ${{ secrets.DOCKERHUB_USERNAME }}
           # password: ${{ secrets.DOCKERHUB_TOKEN }}
     steps: 
       - name: Test Mvn
         run: mvn -v
