name: Ant teste
on: workflow_dispatch
jobs:
    Test:
     runs-on: ubuntu-latest
     container:
        image: idrigotti/java-ant
     steps: 
       - name: Java Version
         run: java -version
       - name: Ant Version
         run: ant -v