name: Ant teste
on: workflow_dispatch
jobs:
    Test:
     runs-on: ubuntu-latest
     steps: 
       - name: Set up Ant
         uses: cedx/setup-ant@v3
         with:
           optional-tasks: true
           version: =1.7.1
       - name: Ant Version
         run: ant -v