name: Ant test
on: workflow_dispatch
jobs:
    Build:
     runs-on: ubuntu-latest
     container:
        image: idrigotti/java-ant
     steps: 
       - name: Get Action
         uses: actions/checkout@v3
       - name: Java e Ant Version
         uses: ant build
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
         with:
          name: build-files
          path: /jar/ant-sample.jar