name: Ant teste
on: workflow_dispatch
jobs:
    Test:
     runs-on: ubuntu-latest
#     container:
#        image: idrigotti/java-ant
     steps: 
       - name: Get Action
         uses: actions/checkout@v3
       - name: List Directories
         run: |
            pwd
            ls
       - name: Java e Ant Version
         uses: ./.github/actions/ant-docker