name: Ant test
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
    Build:
     runs-on: self-hosted
     container:
        image: idrigotti/java-ant
     steps: 
       - name: Get Repository
         uses: actions/checkout@v4
       - name: Java e Ant Version
         run: ant build
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
         with:
          name: build-files
          path: |
            /__w/Actions/Actions/build/jar/ant-sample.jar
            index.html
    Package:
      needs: Build
      runs-on: ubuntu-latest
      container:
         image: idrigotti/docker
      steps:
        - name: Get Repository
          uses: actions/checkout@v4
        - name: Download artifacts
          uses: actions/download-artifact@v4
          with: 
           name: build-files
        - name: Build image
          run: docker build --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/apache:latest . 
        - name: Login Docker
          run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        - name: Push Docker
          run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/apache:latest
    Deploy:
      needs: Package
      runs-on: ubuntu-latest
      container:
         image: idrigotti/openshift
      steps:
        - name: Deploy
          run: |
            oc version
            kubectl version
      